language: scala
jdk: oraclejdk8
sudo: false
scala:
- 2.11.7
sbt_args: "-no-colors -J-Xss2m"
env:
  global:
    secure: JSKBh7CD4JFgKAEdN6T5CCrfNxhuTLC+/Km4b7jMEK5LRYA3Kn++0TFR2DqtcVPRvAI/VrF12pvJLhRQGdZM7i1ws8I2yHWpDEigXusQ2x07TkFzowRcj0s0Y4q51F6ht1kdUJnRpQlr2F2pLveFev8whKEoPjMEm2J5LRLO/sM7EAusGFybIYQesgZ3JcfBdDZ72aHsLSE6tHSIN6yILtyZzy94/fKT/BVo7a3y7FSYw0Q1omNmtvSYHfKF1P083TOHU1wc3kHyh2l5dQwWMAJ66NVSD+NCp5ohiGyV/YzQj0Oa13xY/6m7X0n0vLoZRidERdroj2GVtfZ5v/kuQMt6DknFfINHh2VSbEv3KLk7/s3kEJDL0ps7XH/EZR6vSXs9gQyskMjKqVF7ShfEWOXCmanqaBYVEy9EewIdbcV/Fj0ODneoL2CzcTWSRJipsPt+J5AIYzf51Ur4YYniLdnxS2neW1feL1x2nixhE8/VCExxbMxmUXfbGK8eARaI6CqEtOVITG0fgSG+sxZECys1lrCCwmcLL19ldUyq+G2oLEkwDUAOzxOYLwqRnE10ZiwqfviuEDR2TgkJteQnSrJ2mCTOcwCF830X/0lh/XuPUxcHKkd4IMg/UBS1o+TOF4L77yC4dMxBuXopdYcUQPzbFIbZiiP9YvcMlpUiXXA=
    POSTGRESQL_DB_HOST=ec2-54-197-230-161.compute-1.amazonaws.com
    POSTGRESQL_DB_NAME=d4ulp3l3672aev
    POSTGRESQL_DB_USER=ymudubmcygrxqj
    POSTGRESQL_DB_PASSWORD=placeholder
    POSTGRESQL_DB_PORT=5432
deploy:
  provider: heroku
  api_key:
    secure: mLWQ5fwZUgMPVCfF0ste6hBo3N4wV1WluxkXedyKAKoMoLLC39fBpMjiIdYi7nKaNAaM1JE3ri8H37+FHkTqbvZfpopoq2IcnODgjVKATSvSrDyLGsUiN1vXD4M4lenrLmbNGGl0IvtUkN4iy6SprfxBS3ruS0A39q97UAKizOVKXp/gckmwEFH0k3ZQetufMRfsRH+Inwn7+3CQ/HGMnH5VmBFMbDt9I5tpHVfqkSaFwxHdXy/QFqpdSW6osRymCrSogXKeeC6KWTlVdD3XwjwLe6n14MQBRjxLLBD9fHdTI4iiTLa113G0ud5ZsgifrgycYq3dN3uBmMwull65EQVcuXipWQOXsIZzde82cJElcEbolF9vxMAtb8BHDJ6G/2t+Vaf4vTmRVinkeCJ5Bk165bWaUWZgAQEXBlGPMXnRYp0btSrIN1ANQ/3CHfbFS6j3CjaoMsLDEYWAWHuKCWLb75/XikPH4Gch273aMb15SrKLfBdSy/mT4Z4qOsXIDbtZGoK7pZrjiBXohBmz8NDODgGMhxeJzZv/BylUzfVvLuv9wql2IPFUlxSlV1o7C8EuFgeZFOeXcKyKvOoE4Ghw/QwqZppcxcjJfmNiaBbBgYcD6tKvU+xqGmtGNlCDZhCBp3hRmwxYhZT/BjRZ3M0Ngfeih8SBszQHl1v9UXg=
  app: sisdn
  on:
    repo: mhashimm/backend
    branch: heroku-master
