language: scala
jdk: oraclejdk8
sudo: false
scala:
- 2.11.7
sbt_args: "-no-colors -J-Xss2m"
deploy:
  provider: heroku
  user: mhashim.gm@gmail.com
  password:
    secure: TkBegWHN+08V+xhDbatf/nI9uvDCa2QwEn9QZZXmqOWpjVArORYlj0k59oUP8hgD5eLI/942kB3e0Dwv9X3vVx7Ous8QJ5UV4qBdtE3sTNu5MZvEXFgDtosEJvmFmc3U+gdyHDwpyc8a6iYZqypPPt9x9+byxMDAxdHrc85grMQbGrxi/a8JsR2kD4RpbRskNLzL+6h5R1FXDauZeciV39HO95lJmwTeQyGjlPbukRmP9KeHdkTSm60sGeN2HbmHmGZ6jmCHt9OI5zliSPbV+Enjr8PbRTRj3fu6+a461/xZOQdjsE+oDdadf3eNUdca6T6ncF8o1CCGJWJnxHYUXiCPZi0dD02QZNx3faXbJAwCC9eza6NRCUfxnO1H4ADRiaDsKuUDe50hIKwqPkw83s0Ix2cIZ9EWpxoDmFIAhfgIru5sFFPtI+vIjemhhOykChl5ttkNq9Y5nZqy+v9Bygwro2iEQGnE4TQ+3UisrP0+ewhEwLEdPL+telXvEx2K/ieXxqy/Jta/7/LzfX6Bh9D9v2BTovRMtxO6qKoZsA3fStZIeUuoUVn0VVLTYVbUFDc2Tz4tZYtgw8YowViJxGB5F6SrsCeOyh94epNy3OmCQaVi6cKAXbswzamPUCbKi0XsKJ6joDRZCIbq1rZ4fdhlSmV98LDLOYVE5t3sRGk=
  app: sisdn
  domain: sisdn
  on:
    repo: mhashimm/backend
    branch: heroku-master
  api_key:
    secure: wWQVYGLA8SDLW149hX+x834P2/yDvO8VOJiqqdFZF3FcxojYVJOJF798aeigujOZGJgKM4Cgvgj70GYRENuxYG3KiAtfnI7j8JtWz0Sfl74/t2JAbhA9Y/z8av1Ruy/W5cnz+9SME1k4woh32wLAeSo8QiaULE6oleGkzv7weH/UO9IIvKmLpnAcoQoqNfpbYfC0OmB4vf86n6T/Oudok+YSFIxIxLxNjHYOhGGI5Ko7ZG0kgUkcLxGT9wDQXf9nEYtdDp/bII8GAwEzsLxmSWfU/VsVP8sI52xzlkI8iSixhmuy+swLzShZvNKSya63wn2QBDdd4CuwQs58GVq9UFsiR++izb6N6siTuF9K21IaQMJBNwh0a2A8P9PpLamfYOp6BV5z6hWjN/9oBl37HYGqKzQlkyKPsFsvZq+h67aMfzZUvKAXg2OX52EjOynTJS2O/i9YhT+A87ts59rxXPP821Gv+pmmumJy1m0O9PAwNfyKuNY49ycCSHZaVFAIZMT86ZMtFEhdSaHEXSFaJvvwTKBSssKAJtzGLhZIhJp5E/u9PPz87s2Gyw/Oy2vDQv05jILmwRhn95z+kHznix101yByvoFVcrh+e4xCrSyuEtbe/9X1xrRNGsdkGQbACpNHtTx0wOy2oUuqwtFkHymxitglloBWt1pajbIhsYM=
env:
  global:
    secure: JSKBh7CD4JFgKAEdN6T5CCrfNxhuTLC+/Km4b7jMEK5LRYA3Kn++0TFR2DqtcVPRvAI/VrF12pvJLhRQGdZM7i1ws8I2yHWpDEigXusQ2x07TkFzowRcj0s0Y4q51F6ht1kdUJnRpQlr2F2pLveFev8whKEoPjMEm2J5LRLO/sM7EAusGFybIYQesgZ3JcfBdDZ72aHsLSE6tHSIN6yILtyZzy94/fKT/BVo7a3y7FSYw0Q1omNmtvSYHfKF1P083TOHU1wc3kHyh2l5dQwWMAJ66NVSD+NCp5ohiGyV/YzQj0Oa13xY/6m7X0n0vLoZRidERdroj2GVtfZ5v/kuQMt6DknFfINHh2VSbEv3KLk7/s3kEJDL0ps7XH/EZR6vSXs9gQyskMjKqVF7ShfEWOXCmanqaBYVEy9EewIdbcV/Fj0ODneoL2CzcTWSRJipsPt+J5AIYzf51Ur4YYniLdnxS2neW1feL1x2nixhE8/VCExxbMxmUXfbGK8eARaI6CqEtOVITG0fgSG+sxZECys1lrCCwmcLL19ldUyq+G2oLEkwDUAOzxOYLwqRnE10ZiwqfviuEDR2TgkJteQnSrJ2mCTOcwCF830X/0lh/XuPUxcHKkd4IMg/UBS1o+TOF4L77yC4dMxBuXopdYcUQPzbFIbZiiP9YvcMlpUiXXA=
